services:
  ganache:
    image: trufflesuite/ganache:latest
    ports:
      - "8545:8545"
    command: --deterministic
    restart: unless-stopped
    networks:
      - purechain-network

  app:
    image: gayya/purechain-app:latest
    depends_on:
      - ganache
    env_file:
      - .env
    ports:
      - "3000:3000"
    command: sh -c "sleep 15 && truffle migrate --config truffle-config.cjs && node app.js"
    restart: unless-stopped
    networks:
      - purechain-network

networks:
  purechain-network:
    driver: bridge